In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%pip install seaborn
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

Note: you may need to restart the kernel to use updated packages.


In [6]:
patients = np.array(['SMC01','SMC02','SMC03','SMC04','SMC05','SMC06','SMC07','SMC08','SMC09','SMC10','SMC11','SMC13','SMC14','SMC15','SMC16','SMC17','SMC18','SMC19','SMC20','SMC21','SMC22','SMC23','SMC24','SMC25','SMC171','KUL01','KUL19','KUL21','KUL28','KUL30','KUL31'])

In [7]:
ds1_patients = np.array(['SMC13','SMC171'])
ds2_patients = np.array(['SMC01','SMC02','SMC03','SMC04','SMC05','SMC06','SMC07','SMC08','SMC09','SMC10','SMC11','SMC14','SMC15','SMC16','SMC17','SMC18','SMC19','SMC20','SMC21','SMC22','SMC23','SMC24','SMC25'])
ds3_patients = np.array(['KUL01','KUL19','KUL21','KUL28','KUL30','KUL31'])

In [8]:
p_train,p_test=train_test_split(patients,test_size = 0.1, train_size = 0.8)

In [9]:
p_train

array(['SMC20', 'SMC19', 'SMC16', 'SMC23', 'SMC17', 'KUL21', 'SMC22',
       'SMC171', 'SMC02', 'SMC01', 'SMC10', 'SMC14', 'SMC21', 'KUL28',
       'SMC18', 'SMC13', 'SMC04', 'SMC03', 'SMC24', 'SMC05', 'KUL31',
       'KUL30', 'SMC25', 'SMC11'], dtype='<U6')

In [10]:
p_test

array(['KUL01', 'SMC09', 'KUL19', 'SMC15'], dtype='<U6')

In [11]:
p_validation = patients
p_validation = p_validation.tolist()
for i in range(len(p_train)):
    K = p_train[i]
    while (K in p_validation):
        p_validation.remove(K)
for i in range(len(p_test)):
    K = p_test[i]
    while (K in p_validation):
        p_validation.remove(K)

In [12]:
p_validation

['SMC06', 'SMC07', 'SMC08']

In [13]:
p_val = p_validation

In [14]:
dataset1_annotation = pd.read_csv("GSE132257_processed_protocol_and_fresh_frozen_cell_annotation.txt", header=0, sep='\t')
dataset2_annotation = pd.read_csv("GSE132465_GEO_processed_CRC_10X_cell_annotation.txt",header=0,sep='\t')
dataset3_annotation = pd.read_csv("GSE144735_processed_KUL3_CRC_10X_annotation.txt",header=0,sep='\t')

In [15]:
dataset1_annotation = dataset1_annotation.to_numpy()
dataset2_annotation = dataset2_annotation.to_numpy()
dataset3_annotation = dataset3_annotation.to_numpy()

In [16]:
dataset1_annotation

array([['SMC13N-A1-F_AAACCTGAGATCGGGT', 'SMC13', 'Normal', 'Frozen',
        'SMC13N-A1-F', 'T cells'],
       ['SMC13N-A1-F_AAACCTGAGGATTCGG', 'SMC13', 'Normal', 'Frozen',
        'SMC13N-A1-F', 'T cells'],
       ['SMC13N-A1-F_AAACCTGGTACTCAAC', 'SMC13', 'Normal', 'Frozen',
        'SMC13N-A1-F', 'T cells'],
       ...,
       ['SMC171-T-SING_TTTGTCAAGGTGCTAG', 'SMC171', 'Tumor',
        'SING protocol', 'SMC171-T-SING', 'T cells'],
       ['SMC171-T-SING_TTTGTCACAGCATACT', 'SMC171', 'Tumor',
        'SING protocol', 'SMC171-T-SING', 'Epithelial cells'],
       ['SMC171-T-SING_TTTGTCAGTCTGGAGA', 'SMC171', 'Tumor',
        'SING protocol', 'SMC171-T-SING', 'Epithelial cells']],
      dtype=object)

In [20]:
arr = np.concatenate((dataset1_annotation,dataset2_annotation))

In [21]:
arr

array([['SMC13N-A1-F_AAACCTGAGATCGGGT', 'SMC13', 'Normal', 'Frozen',
        'SMC13N-A1-F', 'T cells'],
       ['SMC13N-A1-F_AAACCTGAGGATTCGG', 'SMC13', 'Normal', 'Frozen',
        'SMC13N-A1-F', 'T cells'],
       ['SMC13N-A1-F_AAACCTGGTACTCAAC', 'SMC13', 'Normal', 'Frozen',
        'SMC13N-A1-F', 'T cells'],
       ...,
       ['SMC10-N_TGCTACCGTCTCCATC', 'SMC10', 'Normal', 'SMC10-N',
        'Mast cells', 'Mast cells'],
       ['SMC10-N_TTTATGCAGTGTCTCA', 'SMC10', 'Normal', 'SMC10-N',
        'Mast cells', 'Mast cells'],
       ['SMC10-N_TTTGGTTAGTGCCATT', 'SMC10', 'Normal', 'SMC10-N',
        'Mast cells', 'Mast cells']], dtype=object)

In [22]:
full_data = np.concatenate((arr,dataset3_annotation))

In [23]:
full_data

array([['SMC13N-A1-F_AAACCTGAGATCGGGT', 'SMC13', 'Normal', 'Frozen',
        'SMC13N-A1-F', 'T cells'],
       ['SMC13N-A1-F_AAACCTGAGGATTCGG', 'SMC13', 'Normal', 'Frozen',
        'SMC13N-A1-F', 'T cells'],
       ['SMC13N-A1-F_AAACCTGGTACTCAAC', 'SMC13', 'Normal', 'Frozen',
        'SMC13N-A1-F', 'T cells'],
       ...,
       ['KUL31-N_GCCTCTATCGCGGATC', 'KUL31', 'Normal', 'KUL31-N',
        'Mast cells', 'Mast cells'],
       ['KUL31-N_GGGATGATCACCTCGT', 'KUL31', 'Normal', 'KUL31-N',
        'Mast cells', 'Mast cells'],
       ['KUL31-N_TTAGTTCTCGGTCCGA', 'KUL31', 'Normal', 'KUL31-N',
        'Mast cells', 'Mast cells']], dtype=object)

In [24]:
len(full_data)

109512

In [25]:
col1 = full_data[:,0]

In [26]:
col2 = full_data[:,1]
col3 = full_data[:,2]

In [27]:
data = np.column_stack((col1,col2))

In [28]:
col3 = np.arange(109512)

In [29]:
trun_data = np.column_stack((data,col3))

In [30]:
trun_data

array([['SMC13N-A1-F_AAACCTGAGATCGGGT', 'SMC13', 0],
       ['SMC13N-A1-F_AAACCTGAGGATTCGG', 'SMC13', 1],
       ['SMC13N-A1-F_AAACCTGGTACTCAAC', 'SMC13', 2],
       ...,
       ['KUL31-N_GCCTCTATCGCGGATC', 'KUL31', 109509],
       ['KUL31-N_GGGATGATCACCTCGT', 'KUL31', 109510],
       ['KUL31-N_TTAGTTCTCGGTCCGA', 'KUL31', 109511]], dtype=object)

In [49]:
cell_IDs_train = np.array([])
indices_train = np.array([])

#cell_IDs_test = np.array([])
#indices_test = np.array([])

#cell_IDs_val = np.array([])
#indices_val = np.array([]).astype(int)

for i in range(len(p_train)): #for every patient in training set
    for d1 in range(len(ds1_patients)):#find out if patient is in first dataset 1
        if p_train[i] == ds1_patients[d1]: #if patient is in dataset1
            for x in range(len(dataset1_annotation)): #
                if p_train[i] == trun_data[x,1]: # if the patient in the training set matches the patient in dataset 1
                    cell_IDs_train = np.append(cell_IDs_train,trun_data[x,0]) #record the id
                    indices_train = np.append(indices_train,trun_data[x,2]) #record the index
    
    for d2 in range(len(ds2_patients)): #find out if patient is in first dataset 1
        if p_train[i] == ds2_patients[d2]: #if patient is in dataset1
            for x in range(len(dataset2_annotation)): #
                if p_train[i] == trun_data[len(dataset1_annotation)+x,1]: # if the patient in the training set matches the patient in dataset 1
                    cell_IDs_train = np.append(cell_IDs_train,trun_data[len(dataset1_annotation)+x,0]) #record the id
                    indices_train = np.append(indices_train,trun_data[len(dataset1_annotation)+x,2]) #record the index
    
    for d3 in range(len(ds3_patients)): #find out if patient is in first dataset 1
        if p_train[i] == ds3_patients[d3]: #if patient is in dataset1
            for x in range(len(dataset3_annotation)): #
                if p_train[i] == trun_data[len(dataset2_annotation)+len(dataset1_annotation)+x,1]:
                   # print(trun_data[len(dataset2_annotation)+len(dataset1_annotation)+x,2])# if the patient in the training set matches the patient in dataset 1
                    cell_IDs_train = np.append(cell_IDs_train,trun_data[len(dataset2_annotation)+len(dataset1_annotation)+x,0]) #record the id
                    indices_train = np.append(indices_train,trun_data[len(dataset2_annotation)+len(dataset1_annotation)+x,2]) #record the index
                                   

In [51]:
cell_IDs_train

array(['SMC20-T_AAACGGGGTAGCACGA', 'SMC20-T_AAAGATGGTTTGACTG',
       'SMC20-T_AAAGCAACAAGACACG', ..., 'SMC11-T_TTTGCGCAGATACACA',
       'SMC11-T_TTTGCGCCAGTTCCCT', 'SMC11-T_TTTGGTTCAGGATCGA'],
      dtype='<U32')

In [52]:
indices_train

array([30353., 30354., 30355., ..., 75100., 75101., 75102.])

In [53]:
dummy1 =np.array(indices_train,dtype='int32')
dummy1

array([30353, 30354, 30355, ..., 75100, 75101, 75102])

In [32]:
#cell_IDs_train = np.array([])
#indices_train = np.array([])

cell_IDs_test = np.array([])
indices_test = np.array([])

#cell_IDs_val = np.array([])
#indices_val = np.array([]).astype(int)

for i in range(len(p_test)): #for every patient in training set
    for d1 in range(len(ds1_patients)):#find out if patient is in first dataset 1
        if p_test[i] == ds1_patients[d1]:
            #if patient is in dataset1
            for x in range(len(dataset1_annotation)): #
                if p_test[i] == trun_data[x,1]: # if the patient in the training set matches the patient in dataset 1
                    cell_IDs_test = np.append(cell_IDs_test,trun_data[x,0]) #record the id
                    indices_test = np.append(indices_test,trun_data[x,2]) #record the index
    
    for d2 in range(len(ds2_patients)): #find out if patient is in first dataset 1
        if p_test[i] == ds2_patients[d2]: #if patient is in dataset1
            for x in range(len(dataset2_annotation)): #
                if p_test[i] == trun_data[len(dataset1_annotation)+x,1]: # if the patient in the training set matches the patient in dataset 1
                    cell_IDs_test = np.append(cell_IDs_test,trun_data[len(dataset1_annotation)+x,0]) #record the id
                    indices_test = np.append(indices_test,trun_data[len(dataset1_annotation)+x,2]) #record the index
    
    for d3 in range(len(ds3_patients)): #find out if patient is in first dataset 1
        if p_test[i] == ds3_patients[d3]: #if patient is in dataset1
            for x in range(len(dataset3_annotation)): #
                if p_test[i] == trun_data[len(dataset2_annotation)+len(dataset1_annotation)+x,1]:
                   # print(trun_data[len(dataset2_annotation)+len(dataset1_annotation)+x,2])# if the patient in the training set matches the patient in dataset 1
                    cell_IDs_test = np.append(cell_IDs_test,trun_data[len(dataset2_annotation)+len(dataset1_annotation)+x,0]) #record the id
                    indices_test = np.append(indices_test,trun_data[len(dataset2_annotation)+len(dataset1_annotation)+x,2]) #record the index
                                   

In [45]:
indices_test

array([82098., 82099., 82100., ..., 75538., 75539., 75540.])

In [54]:
dummy2 = np.array(indices_test,dtype='int32')
dummy2

array([82098, 82099, 82100, ..., 75538, 75539, 75540])

In [57]:
#cell_IDs_train = np.array([])
#indices_train = np.array([])

#cell_IDs_test = np.array([])
#indices_test = np.array([])

cell_IDs_val = np.array([])
indices_val = np.array([]).astype(int)

for i in range(len(p_val)): #for every patient in training set
    for d1 in range(len(ds1_patients)):#find out if patient is in first dataset 1
        if p_val[i] == ds1_patients[d1]:
            #if patient is in dataset1
            for x in range(len(dataset1_annotation)): #
                if p_val[i] == trun_data[x,1]: # if the patient in the training set matches the patient in dataset 1
                    cell_IDs_val = np.append(cell_IDs_val,trun_data[x,0]) #record the id
                    indices_val = np.append(indices_val,trun_data[x,2]) #record the index
    
    for d2 in range(len(ds2_patients)): #find out if patient is in first dataset 1
        if p_val[i] == ds2_patients[d2]: #if patient is in dataset1
            for x in range(len(dataset2_annotation)): #
                if p_val[i] == trun_data[len(dataset1_annotation)+x,1]: # if the patient in the training set matches the patient in dataset 1
                    cell_IDs_val = np.append(cell_IDs_val,trun_data[len(dataset1_annotation)+x,0]) #record the id
                    indices_val = np.append(indices_val,trun_data[len(dataset1_annotation)+x,2]) #record the index
    
    for d3 in range(len(ds3_patients)): #find out if patient is in first dataset 1
        if p_val[i] == ds3_patients[d3]: #if patient is in dataset1
            for x in range(len(dataset3_annotation)): #
                if p_val[i] == trun_data[len(dataset2_annotation)+len(dataset1_annotation)+x,1]:
                   # print(trun_data[len(dataset2_annotation)+len(dataset1_annotation)+x,2])# if the patient in the training set matches the patient in dataset 1
                    cell_IDs_val = np.append(cell_IDs_val,trun_data[len(dataset2_annotation)+len(dataset1_annotation)+x,0]) #record the id
                    indices_val = np.append(indices_val,trun_data[len(dataset2_annotation)+len(dataset1_annotation)+x,2]) #record the index
                                   

In [58]:
cell_IDs_val

array(['SMC06-T_AAAGTAGGTTCCCTTG', 'SMC06-T_AACACGTAGCTAACTC',
       'SMC06-T_AACTCTTGTGAGCGAT', ..., 'SMC08-N_TGTGTTTCAATGCCAT',
       'SMC08-N_TGTTCCGTCTCAACTT', 'SMC08-N_TTAACTCGTAGAGTGC'],
      dtype='<U32')

In [59]:
indices_val

array([20970, 20971, 20972, ..., 82061, 82062, 82063])

In [61]:
dummy3 = np.array(indices_val,dtype='int32')
dummy3

array([20970, 20971, 20972, ..., 82061, 82062, 82063])

In [62]:
val_check = pd.DataFrame(indices_val)

In [63]:
val_check.to_csv("val_check", sep='\t',index = False)

In [64]:
training_set = np.column_stack((cell_IDs_train,dummy1))

In [65]:
training_set

array([['SMC20-T_AAACGGGGTAGCACGA', '30353'],
       ['SMC20-T_AAAGATGGTTTGACTG', '30354'],
       ['SMC20-T_AAAGCAACAAGACACG', '30355'],
       ...,
       ['SMC11-T_TTTGCGCAGATACACA', '75100'],
       ['SMC11-T_TTTGCGCCAGTTCCCT', '75101'],
       ['SMC11-T_TTTGGTTCAGGATCGA', '75102']], dtype='<U32')

In [66]:
test_set = np.column_stack((cell_IDs_test,dummy2))

In [67]:
test_set

array([['KUL01-T_AAACCTGGTCTTTCAT', '82098'],
       ['KUL01-T_AAACGGGTCGGTTAAC', '82099'],
       ['KUL01-T_AAAGATGGTATAGGGC', '82100'],
       ...,
       ['SMC15-T_TTTGCGCTCATCTGTT', '75538'],
       ['SMC15-T_TTTGGTTAGTCGTTTG', '75539'],
       ['SMC15-T_TTTGGTTTCTACCAGA', '75540']], dtype='<U32')

In [68]:
val_set = np.column_stack((cell_IDs_val,dummy3))

In [69]:
val_set

array([['SMC06-T_AAAGTAGGTTCCCTTG', '20970'],
       ['SMC06-T_AACACGTAGCTAACTC', '20971'],
       ['SMC06-T_AACTCTTGTGAGCGAT', '20972'],
       ...,
       ['SMC08-N_TGTGTTTCAATGCCAT', '82061'],
       ['SMC08-N_TGTTCCGTCTCAACTT', '82062'],
       ['SMC08-N_TTAACTCGTAGAGTGC', '82063']], dtype='<U32')

In [73]:
new_pd_val_set = pd.DataFrame(val_set)
new_pd_train_set = pd.DataFrame(training_set)
new_pd_test_set = pd.DataFrame(test_set)

In [71]:
new_pd_val_set[1] = new_pd_val_set[1].astype(int)
new_pd_train_set[1] = new_pd_train_set[1].astype(int)
new_pd_test_set[1] = new_pd_test_set[1].astype(int)


In [74]:
new_pd_val_set.to_csv("patient_split_validation.tsv", sep='\t',index = False)
new_pd_train_set.to_csv("patient_split_train.tsv", sep='\t',index = False)
new_pd_test_set.to_csv("patient_split_test.tsv", sep='\t',index = False)